### ISSUE TITLE
request for source code

### ISSUE THREAD

**Issue by CharizardAcademy** [U-Alberta/AMRS3#1]
Dear authors, 

Thank you for your paper "Semantic Graphs for Syntactic Simplification: A Revisit from the Age of LLM." We found it very inspiring. 

Could you share the source code for your research so we can compare it with our own implementation? 

many thanks!

**Comment by xavieryao** [comment]
Hi Yingqiang,

Thank you so much for your interest! I apologize for the delay in updating the repository — we've been working through some licensing issues with the data alongside other pressing tasks.

In the meantime, we’ve uploaded the code and pre-trained model to make it possible for you to start with running the pipeline and producing outputs. Please don’t hesitate to reach out if you encounter any issues running the pipelines or if there’s anything you’d like to discuss. We’re still working on code to replicate the dataset and pre-training steps.

But as we discussed in the paper, prompting a modern LLM is a great solution these days unless there are niche needs :) Good luck!
